[[redirects]]
  from = "/pdchatbot/api/*"
  to = "https://brainbook-chat.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pdchatbot/predict"
  to = "https://brainbook-chat.onrender.com/predict"
  status = 200
  force = true

[[redirects]]
  from = "/pdchatbot/"
  to = "/pdchatbot/templates/apartado_inteligente.html"
  status = 200
